### ISSUE TITLE
It does not work with Email Auth

### ISSUE THREAD

**Issue by victorshinya** [gabrieldrs/node-steam-card-farm#6]
First I tried with Email Auth (my default authentication method) but it did not work. It displayed a message 'Password incorrect'. However, when I tried to authenticate with my Steam iOS App, it worked!

**Comment by gabrieldrs** [comment]
Hey, thanks for the feedback, I will try to solve this issue and report back!

**Comment by gabrieldrs** [comment]
This was solved on 9edf41c

**Comment by gabrieldrs** [comment]
Hey Victor, thanks again for the report.
This has just been solved on 9edf41c
